AddressBook/AddressBookMVC/Controllers/QuickListController.cs
using AddressBook.BLL.Service;
using AddressBook.Interfaces.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AddressBookMVC.Controllers
{
    [Authorize]
    public class QuickListController : Controller
    {
        QuickListService _quickListService = new QuickListService();
        ContactService _contactService = new ContactService();

        [HttpGet]
        public ActionResult Create()
        {
            int contactId = _contactService.GetContactByLogin(User.Identity.Name).Ob.ContactId;
            ViewData["contactId"] = contactId;
            return View("Create");
        }

        [HttpPost]
        public ActionResult Create(QuickList quickList)
        {
            var contentResult = _quickListService.Create(quickList);
            if (contentResult.Success)
            {
                return RedirectToAction("Index");
            }
            return View("/Views/Shared/Error.cshtml");
        }

        public ActionResult Index()
        {
            //var contentResult1 = _quickListService.GetContactByLogin(User.Identity.Name);
            //if (contentResult1.Success)
            //{
                var contentResult2 = _quickListService.GetAll(User.Identity.Name);
                if (contentResult2.Success)
                {
                    return View("Index", contentResult2.List);
                }
                return View("/Views/Shared/Error.cshtml");
            //}
            //return View("/Views/Shared/Error.cshtml", (object)contentResult1.ErrorMessage);
        }

        [HttpGet]
        public ActionResult ChooseQuickList(int ContactId)
        {
            var contactId = _contactService.GetContactByLogin(User.Identity.Name).Ob.ContactId;
            var result = _quickListService.GetQuickLists(contactId);
            if (result.Success)
            {
                ViewBag.QuickLists = new SelectList(result.List, "QuickListId", "Name");
                ViewData["Id"] = ContactId;
                return PartialView("ChooseQuickList");
            }
            return PartialView("AddToQuickList");
        }

        [HttpPost]
        public ActionResult ChooseQuickList(int ContactId, int QuickListId)
        {
            var result = _quickListService.AddContactToQuickList(ContactId, QuickListId);
            if (result.Success)
            {
                return RedirectToAction("Index");
            }
            return View("/Views/Shared/Error.cshtml"/*, (object)result.Message*/);
        }
    }
}

AddressBook/AddressBookMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Address Book", "Index", "Contact", new { area = "" }, new { @class = "navbar-brand" })
             </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contacts", "Index", "Contact")</li>
                    <li>@Html.ActionLink("Edit profile", "Edit", "Contact",null,htmlAttributes:null )</li>
                    <li>@Html.ActionLink("Quick Lists", "Index", "QuickList")</li>
                </ul>

                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><span style="color:white">Hello, @User.Identity.Name</span></li>
                        <li>@Html.ActionLink("Sign Out", "SignOut", "Contact")</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Register", "SignUp", "Contact", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("Log In", "LogIn", "Contact", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    </ul>
                }
                </div> 
            </div>
        </div>

    <div class="container body-content ">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            <p>Vlad Lutsenko - Beginner .NET developer</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery@*")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
</body>
</html>